version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
    restart: always
    volumes:
      - ${DATA}:/data:Z
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
#    ports:
#      - "3000:3000"
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true