version: '3.8'
networks:
  reverseproxy-nw:
    external: true

services:
  ollama:
    volumes:
      - ${OLLAMA_ROOT_DATA}:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - reverseproxy-nw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ${OLLAMA_WEB_UI_DATA}:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 7870:8080
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=True
      - WEBUI_NAME=${WEBUI_NAME}
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - USE_CUDA_DOCKER=True
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - reverseproxy-nw
