version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    network_mode: host
    volumes:
      - ${CONFIG_DIR}:/config
      - ${TRANSCODE_DIR}:/transcode
      - ${MOVIES_DIR}:/Movies
      - ${TV_DIR}:/TV
    ports:
      - 0.0.0.0:32400:32400/tcp