version: "3"
services:
  haugene-transmission-openvpn1:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    environment:
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/data/watch
      - PUID=${PUID}
      - PGID=${PGID}
      - PEER_DNS=true
      - PEER_DNS_PIN_ROUTES=true
      - HEALTH_CHECK_HOST=google.com
      - TZ=${TZ}
      - OPENVPN_OPTS=${OPENVPN_OPTS}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - DISABLE_PORT_UPDATER=${DISABLE_PORT_UPDATER}
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    ports:
      - 9091:9091/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DATA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
      - ${RESOLV_CONF}:/etc/resolv/conf
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true
