---
version: "2.1"
services:
  netbox:
    image: lscr.io/linuxserver/netbox
    container_name: netbox
    depends_on:
      - postgres
      - redis
      - redis-cache
    links:
      - postgres
      - redis
      - redis-cache
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - ALLOWED_HOST=${ALLOWED_HOST}
      #- DB_NAME=<DB_NAME>
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #- DB_HOST=<DB_HOST>
      #- DB_PORT=<DB_PORT>
      #- REDIS_HOST=<REDIS_HOST>
      #- REDIS_PORT=<REDIS_PORT>
      #- REDIS_PASSWORD=<REDIS_PASSWORD>
      #- REDIS_DB_TASK=<REDIS_DB_TASK>
      #- REDIS_DB_CACHE=<REDIS_DB_CACHE>
      #- BASE_PATH=<BASE_PATH> #optional
      #- REMOTE_AUTH_ENABLED=<REMOTE_AUTH_ENABLED> #optional
      #- REMOTE_AUTH_BACKEND=<REMOTE_AUTH_BACKEND> #optional
      #- REMOTE_AUTH_HEADER=<REMOTE_AUTH_HEADER> #optional
      #- REMOTE_AUTH_AUTO_CREATE_USER=<REMOTE_AUTH_AUTO_CREATE_USER> #optional
      #- REMOTE_AUTH_DEFAULT_GROUPS=<REMOTE_AUTH_DEFAULT_GROUPS> #optional
      #- REMOTE_AUTH_DEFAULT_PERMISSIONS=<REMOTE_AUTH_DEFAULT_PERMISSIONS> #optional
    volumes:
      - ${CONFIG}:/config
    #ports:
    #  - 8000:8000
    restart: unless-stopped
    networks:
      - netbox-nw
      - reverseproxy-nw
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - netbox-nw
  redis:
    image: redis:latest
    networks:
      - netbox-nw
  redis-cache:
    image: redis:latest
    networks:
      - netbox-nw
networks:
  netbox-nw:
  reverseproxy-nw:
    external: true
