version: "3"
services:
  sonarr:
    container_name: sonarr
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_CONFIG_HOME=/config/xdg
      - SONARR_BRANCH=master
      - PGID=${SONARR_GID}
      - PUID=${SONARR_UID}
      - TZ=${TZ}
    hostname: sonarr
    image: linuxserver/sonarr:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    #ports:
    #  - 0.0.0.0:8989:8989/tcp
    #  - 0.0.0.0:9898:9898/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${TV_DIR}:/tv
      - ${CONFIG_DIR}:/config
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true
