---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATA}:/config
    #ports:
    #  - 8181:8181
    restart: unless-stopped
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true