version: "3"
services:
  radarr:
    container_name: radarr
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_CONFIG_HOME=/config/xdg
      - TZ=${TZ}
      - PGID=${RADARR_GID}
      - PUID=${RADARR_UID}
      - UMASK_SET=000
    hostname: radarr
    image: linuxserver/radarr:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    #ports:
    #  - 0.0.0.0:7878:7878/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${MOVIES_DIR}:/movies
      - ${CONFIG_DIR}:/config
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true