version: '3.1'
networks:
  reverseproxy-nw:
    external: true

services:
  jackett:
    container_name: jackett
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_DATA_HOME=/config
      - XDG_CONFIG_HOME=/config
      - AUTO_UPDATE=true
      - TZ=${TZ}
      - PGID=${JACKETT_PGID}
      - PUID=${JACKETT_PUID}
    hostname: jackett
    image: linuxserver/jackett:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    #ports:
    #  - 9117:9117/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${JACKETT_DIR}:/config
    networks:
      - reverseproxy-nw

  radarr:
    container_name: radarr
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_CONFIG_HOME=/config/xdg
      - TZ=${TZ}
      - PGID=${RADARR_GID}
      - PUID=${RADARR_UID}
      - UMASK_SET=000
    hostname: radarr
    image: linuxserver/radarr:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    #ports:
    #  - 0.0.0.0:7878:7878/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${MOVIES_DIR}:/movies
      - ${RADARR_DIR}:/config
      - ${DOWNLOADS_DIR}:/downloads
    networks:
      - reverseproxy-nw

  sonarr:
    container_name: sonarr
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - XDG_CONFIG_HOME=/config/xdg
      - SONARR_BRANCH=master
      - PGID=${SONARR_GID}
      - PUID=${SONARR_UID}
      - TZ=${TZ}
    hostname: sonarr
    image: linuxserver/sonarr:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    #ports:
    #  - 0.0.0.0:8989:8989/tcp
    #  - 0.0.0.0:9898:9898/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${TV_DIR}:/tv
      - ${SONARR_DIR}:/config
      - ${DOWNLOADS_DIR}:/downloads
    networks:
      - reverseproxy-nw

  unpackerr:
    image: "golift/unpackerr"
    container_name: "unpackerr"
    volumes:
      - ${DOWNLOADS_DIR}:/data/downloads
    restart: always
    environment:
      - PUID=${UNPACKERR_PUID}
      - PGID=${UNPACKERR_PGID}
      - TZ=${TZ}
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=None
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API}
      - UN_SONARR_0_PATHS_0=/data/downloads/sonarr
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API}
      - UN_RADARR_0_PATHS_0=/data/downloads/radarr
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
      #- UN_LIDARR_0_URL=http://lidarr:8686
      #- UN_LIDARR_0_API_KEY=
      #- UN_LIDARR_0_PATHS_0=/data/downloads
      #- UN_LIDARR_0_PROTOCOLS=torrent
      #- UN_LIDARR_0_TIMEOUT=10s
      #- UN_LIDARR_0_DELETE_ORIG=false
      #- UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      #- UN_READARR_0_URL=http://readarr:8787
      #- UN_READARR_0_API_KEY=
      #- UN_READARR_0_PATHS_0=/data/downloads
      #- UN_READARR_0_PROTOCOLS=torrent
      #- UN_READARR_0_TIMEOUT=10s
      #- UN_READARR_0_DELETE_ORIG=false
      #- UN_READARR_0_DELETE_DELAY=5m
      # Folder Config
      #- UN_FOLDER_0_PATH=
      #- UN_FOLDER_0_EXTRACT_PATH=
      #- UN_FOLDER_0_DELETE_AFTER=10m
      #- UN_FOLDER_0_DELETE_ORIGINAL=false
      #- UN_FOLDER_0_DELETE_FILES=false
      #- UN_FOLDER_0_MOVE_BACK=false
      # Webhook Config
      #- UN_WEBHOOK_0_URL=
      #- UN_WEBHOOK_0_NAME=
      #- UN_WEBHOOK_0_NICKNAME=Unpackerr
      #- UN_WEBHOOK_0_CHANNEL=""
      #- UN_WEBHOOK_0_TIMEOUT=
      #- UN_WEBHOOK_0_SILENT=false
      #- UN_WEBHOOK_0_IGNORE_SSL=false
      #- UN_WEBHOOK_0_EXCLUDE=[]
      #- UN_WEBHOOK_0_EVENTS=[0]
      #- UN_WEBHOOK_0_TEMPLATE_PATH=""
      #- UN_WEBHOOK_0_CONTENT_TYPE=application/json
    security_opt:
      - no-new-privileges:true
    networks:
      - reverseproxy-nw

  haugene-transmission-openvpn1:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    environment:
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/data/watch
      - PUID=${TRANSMISSION_PUID}
      - PGID=${TRANSMISSION_PGID}
      - PEER_DNS=true
      - PEER_DNS_PIN_ROUTES=true
      - HEALTH_CHECK_HOST=google.com
      - TZ=${TZ}
      - OPENVPN_OPTS=${OPENVPN_OPTS}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - DISABLE_PORT_UPDATER=${DISABLE_PORT_UPDATER}
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    ipc: shareable
    logging:
      driver: local
      options: {}
    ports:
      - 9091:9091/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${TRANSMISSION_DATA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
      - ${RESOLV_CONF}:/etc/resolv/conf
    networks:
      - reverseproxy-nw

  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${TAUTULLI_PUID}
      - PGID=${TAUTULLI_PGID}
      - TZ=${TZ}
    volumes:
      - ${TAUTULLI_DATA}:/config
    #ports:
    #  - 8181:8181
    restart: unless-stopped
    networks:
      - reverseproxy-nw

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    runtime: nvidia
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    network_mode: host
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${TRANSCODE_DIR}:/transcode
      - ${MOVIES_DIR}:/Movies
      - ${TV_DIR}:/TV
    ports:
      - 0.0.0.0:32400:32400/tcp
